apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: gitlab/gitlab-ce:10.5.2-ce.0
      importPolicy: {}
      name: production
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce-redis
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: redis:3.2.3-alpine
      importPolicy: {}
      name: 3.2.3
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      createdBy: gitlab-ce-template
    name: gitlab-ce-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      createdBy: gitlab-ce-template
    name: gitlab-ce-etc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      createdBy: gitlab-ce-template
    name: gitlab-ce-postgresql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      createdBy: gitlab-ce-template
    name: gitlab-ce-redis-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 512Mi
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: builder
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: default
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: deployer
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: gitlab-ce
      deploymentconfig: gitlab-ce
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: gitlab-ce
          deploymentconfig: gitlab-ce
      spec:
        containers:
        - env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: hostname='localhost'; external_url "http://#{hostname}/" unless
              hostname.to_s == ''; root_pass=''; gitlab_rails['initial_root_password']=root_pass
              unless root_pass.to_s == ''; postgresql['enable']=false; gitlab_rails['db_host']
              = 'gitlab-ce-postgresql'; gitlab_rails['db_password']='OqaJnS53XSBpMu7J';
              gitlab_rails['db_username']='userJMY'; gitlab_rails['db_database']='gitlabhq_production';
              redis['enable'] = false; gitlab_rails['redis_host']='gitlab-ce-redis';
              unicorn['worker_processes'] = 2; manage_accounts['enable'] = true; manage_storage_directories['manage_etc']
              = false; gitlab_shell['auth_file'] = '/gitlab-data/ssh/authorized_keys';
              git_data_dirs({ 'default' => { 'path' => '/gitlab-data/git-data' } });
              gitlab_rails['shared_path'] = '/gitlab-data/shared'; gitlab_rails['uploads_directory']
              = '/gitlab-data/uploads'; gitlab_ci['builds_directory'] = '/gitlab-data/builds';
              prometheus_monitoring['enable'] = false;
          image: gitlab/gitlab-ce@sha256:ca60810514f390994e2db3cd5d0a7f973fd5b560607f3c7df3378e3f833d2fbe
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /help
              port: 80
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 2
          name: gitlab-ce
          ports:
          - containerPort: 22
            protocol: TCP
          - containerPort: 80
            protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /help
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/gitlab
            name: gitlab-ce-volume-1
          - mountPath: /gitlab-data
            name: gitlab-ce-volume-2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: gitlab-ce-volume-1
          persistentVolumeClaim:
            claimName: gitlab-ce-etc
        - name: gitlab-ce-volume-2
          persistentVolumeClaim:
            claimName: gitlab-ce-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - gitlab-ce
        from:
          kind: ImageStreamTag
          name: gitlab-ce:production
          namespace: OC_PROJECT_NAME
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce-postgresql
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: gitlab-ce
      deploymentconfig: gitlab-ce-postgresql
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        post:
          execNewPod:
            command:
            - /usr/bin/scl
            - enable
            - rh-postgresql94
            - export PGPASSWORD='wGCmPL0S5PAXglYK'; psql -h 'gitlab-ce-postgresql'
              -U postgres -d gitlabhq_production -c 'CREATE EXTENSION IF NOT EXISTS
              pg_trgm;'
            containerName: gitlab-ce-postgresql
            env:
            - name: HOME
              value: /var/lib/pgsql
            - name: PGDATA
              value: /var/lib/pgsql/data/userdata
            - name: CONTAINER_SCRIPTS_PATH
              value: /usr/share/container-scripts/postgresql
          failurePolicy: Abort
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: gitlab-ce
          deploymentconfig: gitlab-ce-postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: userJMY
          - name: POSTGRESQL_PASSWORD
            value: OqaJnS53XSBpMu7J
          - name: POSTGRESQL_DATABASE
            value: gitlabhq_production
          - name: POSTGRESQL_ADMIN_PASSWORD
            value: wGCmPL0S5PAXglYK
          image: centos/postgresql-94-centos7@sha256:44ac1cd56f0aa019ee7f158df411386d707dd61db63f768282cc38dcc0d0f6f3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          name: gitlab-ce-postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 300Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: gitlab-ce-volume-3
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: gitlab-ce-volume-3
          persistentVolumeClaim:
            claimName: gitlab-ce-postgresql
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - gitlab-ce-postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:9.4
          namespace: openshift
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce-redis
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: gitlab-ce
      deploymentconfig: gitlab-ce-redis
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: gitlab-ce
          deploymentconfig: gitlab-ce-redis
      spec:
        containers:
        - args:
          - exec redis-server
          command:
          - /bin/sh
          - -ec
          image: redis@sha256:49e794b32c129d1ab1ee9f99c0e602f57ea1329aebe641843e0743c8ee336a7e
          imagePullPolicy: IfNotPresent
          name: gitlab-ce-redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 300Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: gitlab-ce-volume-4
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: gitlab-ce-volume-4
          persistentVolumeClaim:
            claimName: gitlab-ce-redis-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - gitlab-ce-redis
        from:
          kind: ImageStreamTag
          name: gitlab-ce-redis:3.2.3
          namespace: OC_PROJECT_NAME
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce
  spec:
    ports:
    - name: 22-ssh
      port: 22
      protocol: TCP
      targetPort: 22
    - name: 80-http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: gitlab-ce
      deploymentconfig: gitlab-ce
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce-postgresql
  spec:
    ports:
    - name: 5432-postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: gitlab-ce
      deploymentconfig: gitlab-ce-postgresql
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce-redis
  spec:
    ports:
    - name: 6379-redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: gitlab-ce
      deploymentconfig: gitlab-ce-redis
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: 'true'
    creationTimestamp: null
    labels:
      app: gitlab-ce
      createdBy: gitlab-ce-template
    name: gitlab-ce
  spec:
    host: gitlab-ce-OC_PROJECT_NAME.127.0.0.1.nip.io
    port:
      targetPort: 80-http
    to:
      kind: Service
      name: gitlab-ce
      weight: 100
    wildcardPolicy: None
kind: List
metadata: {}
