apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: gitlab-secrets
objects:
- apiVersion: v1
  stringData:
    GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    POSTGRESQL_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: gitlab-secrets
  type: Opaque
parameters:
  - name: GITLAB_ROOT_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
  - name: POSTGRESQL_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
  - name: POSTGRESQL_ADMIN_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
